services:

  middleware-jboss:
    image: alpinelinux-jboss:latest

    hostname: middleware-jboss

    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"

    depends_on:
      - database-mssqlserver

    volumes:
      - ./sources/jboss-config.cli:/tmp/jboss-config.cli

  database-mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

    hostname: database-mssqlserver

    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssW0rd
      - MSSQL_PID=Developer

    volumes:
      - database_volume:/var/opt/mssql/
      - ./sources/instnwnd.sql:/tmp/instnwnd.sql

volumes:
  database_volume:


